# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d3c336087a3488b1d2d9785bd4d93d18e0e7cd60efa3ad22391edfbd7d59c967945ab9b8aef50a3e1ffbc07994cfde9016db4227252c68dd984e368e98ca23c

test:
  secret_key_base: 7acbeefdf1f2ff5b0cf09e300156cf8097e226abeee6ccdfc3f5c085934e51a0650f985bb35cc24154c956432a76393aa40738b35bb30ea2ef976836ef70c825

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
